### 获取城市缓存

GET http://localhost:4200/api/v1/cache/dict/cities

### 获取省级行政区 from https://www.juhe.cn

GET http://apis.juhe.cn/xzqh/query?fid=150000&key=6b7fe58a1d86199ad4c25e7fad547e8a

### 登陆

POST http://localhost:4200/api/v1/user/sign-in-user
Content-Type: application/x-www-form-urlencoded

phone=13320354693#password=123456

### 测试接口

GET http://localhost:4200/api/v1/user/test?gender=1&bloodGroup=1&accountStatus=1&date=2020-01-01 12:00:48