spring:
  datasource:
    url: jdbc:mysql://localhost:3306/live_chat?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root